# Site settings
title: "Rapport Tecnológia"
email: "admin@rapport.tec.br"
whatsapp: "(+55 85) 98520-5490"

keywords: ['Rapport Tecnologia', 'Rapport Bot', 'Rapport API', 'Rapport Site', 'consultoria tecnológica', 'automação de atendimento', 'integração de sistemas', 'chatbot', 'agendamento automático', 'pequenos negócios', 'microempresas', 'profissionais liberais', 'autônomos', 'WhatsApp para empresas', 'CRM', 'automação de marketing', 'site personalizado', 'landing pages', 'hospedagem de sites', 'serviços de TI', 'segurança de dados', 'suporte técnico, integração com plataformas de comunicação', 'atendimento automatizado', 'consultoria personalizada', 'soluções digitais', 'otimização de processos', 'API para WhatsApp', 'inteligência artificial', 'integração com Telegram', 'assistente virtual', 'agendamento de horários', 'agendamento online', 'automação de fluxos de trabalho', 'marketing digital', 'Google Analytics', 'SEO', 'ferramentas de automação', 'segurança na comunicação', 'conformidade LGPD', 'site corporativo', 'e-commerce', 'lojas virtuais', 'integração de sistemas de comunicação', 'automação para negócios', 'inovação tecnológica']
description: "Rappot Tecnológia é uma empreendimento fortemente atrelado a intelgiência Artificial, visamos oferecer serviços classicos empoderados tanto por Recursos Humanos como Inteligência Artificial. Temos mais de 35 anos de experiência em integração de sistemas, redes e desenvolvimento de softwares. Da Hospedagem do seu site, até a integração de seus sistemas com meios de comunicação via internet, buscamos a melhor solução."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rapport.tec.br" # the base hostname & protocol for your site
urlimg: "img"
defaultimg: "header.jpg"

twitter_username: ""
github_username: rapporttecnologia

# Build settings
markdown: kramdown

collections:  
  # Ativar posts
  posts:
    output: true
  pages:
    output: true
    permalink: /:path/
  portfolio:
    output: true
    permalink: /projetos/:path/
  contratos:
    output: true
    permalink: /contrato/:path/
  
defaults:
  - 
    scope:
      path: ""
      type: "contratos"
    values:
      image: "header.jpg"

# Definir a estrutura de URL dos posts
permalink: /blog/:categories/:title/
  
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from